resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ingress-nginx-controller
    path: patch-container-resources.yaml
