resources:
  - ../../base
  - patch.yaml

patches:
  - path: patch-container-resources-strategic.yaml

# ArgoCD-specific configurations
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
