apiVersion: batch/v1
kind: Job
metadata:
  name: patch-nginx-deployment
  namespace: ingress-nginx
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      containers:
        - name: patch
          image: lachlanevenson/k8s-kubectl:v1.27.1  # ✅ Works with in-cluster auth
          command:
            - /bin/sh
            - -c
            - |
              echo "🔧 Patching Deployment ingress-nginx-controller with Helm metadata and resources..."
              kubectl patch deployment ingress-nginx-controller -n ingress-nginx \
                --type=merge \
                -p '{
                  "metadata": {
                    "labels": {
                      "app.kubernetes.io/managed-by": "Helm"
                    },
                    "annotations": {
                      "meta.helm.sh/release-name": "ingress-nginx-controller",
                      "meta.helm.sh/release-namespace": "ingress-nginx"
                    }
                  }
                }'
      restartPolicy: Never
