apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-nginx-role
  namespace: ingress-nginx
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-nginx-binding
  namespace: ingress-nginx
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ingress-nginx
roleRef:
  kind: Role
  name: patch-nginx-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-nginx-deployment
  namespace: ingress-nginx
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      containers:
        - name: patch
          image: lachlanevenson/k8s-kubectl:v1.23.0
          command:
            - /bin/sh
            - -c
            - |
              echo "🔧 Patching Deployment ingress-nginx-controller with Helm metadata and resources..."
              kubectl patch deployment ingress-nginx-controller -n ingress-nginx \
                --type=merge \
                -p '{
                  "metadata": {
                    "labels": {
                      "app.kubernetes.io/managed-by": "Helm"
                    },
                    "annotations": {
                      "meta.helm.sh/release-name": "ingress-nginx-controller",
                      "meta.helm.sh/release-namespace": "ingress-nginx"
                    }
                  }
                }'
      restartPolicy: Never
