apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  template:
    spec:
      containers:
        - name: controller
          resources:
            requests:
              cpu: "200m"
              memory: "768Mi"
            limits:
              cpu: "900m"
              memory: "2Gi"
