apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-nginx-base.yaml

patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: ingress-nginx
  - path: nginx-resources-patch.yaml
    target:
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
