apiVersion: batch/v1
kind: Job
metadata:
  name: patch-nginx-deployment
  namespace: ingress-nginx
spec:
  template:
    spec:
      containers:
      - name: patch
        image: bitnami/kubectl:latest
        command:
          - /bin/sh
          - -c
          - |
            echo "Patching ingress-nginx-controller deployment..."
            kubectl patch deployment ingress-nginx-controller -n ingress-nginx \
              --type=merge \
              -p '{"spec":{"template":{"spec":{"containers":[{"name":"controller","resources":{"requests":{"cpu":"100m","memory":"128Mi"},"limits":{"cpu":"500m","memory":"512Mi"}}}]}}}}'
        env:
          - name: KUBECONFIG
            value: /etc/rancher/rke2/rke2.yaml
        volumeMounts:
          - name: kubeconfig
            mountPath: /etc/rancher/rke2
      restartPolicy: OnFailure
      volumes:
      - name: kubeconfig
        hostPath:
          path: /etc/rancher/rke2
